### ISSUE TITLE
Duplicate identifier 'stack' with TS 1.9

### ISSUE THREAD

**Issue by demurgos** [types/env-node#10]
Hi,
Typescript `1.9` (currently `typescript@next`) adds definitions for [`Error.prototype.stack`](https://github.com/nojvek/TypeScript/blob/94d8888b09b1c08737b6311d50335c8c045f7da0/src/lib/es5.d.ts#L867).

It results in [a duplicate identifier](https://github.com/typed-typings/env-node/blob/master/4/node.d.ts#L28)

````text
C:/Users/Charles/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts(883,5): error TS2300: Duplicate identifier 'stack'.
typings/globals/node/index.d.ts(19,3): error TS2300: Duplicate identifier 'stack'.
````

How do you plan to handle this sort of changes ? Should we remove `stack` from this definition once TS 1.9 is stable ?

**Comment by unional** [comment]
I recall there is an issue about expanding `versions` in `typings/registry` to support this. Couldn't find it.

It is something inline with:

```js
{
  "versions": {
    "x.y.z": {
      "typescript": "^1.9",
      "url": "github:typed-typings/node#SHA..."
    }
  }
}
```

**Comment by demurgos** [comment]
Ok, I forgot that you could provide an object instead of a string to describe the typings.

**Comment by unional** [comment]
I don't know if this is implemented or not. There is an suggestion on this.

**Comment by blakeembrey** [comment]
Both back-end and core of Typings can handle the TypeScript version, but since no one has done it yet the experience _may_ need some tweaking. I believe it'll be latest version + TypeScript version by default since it follows semver. See https://github.com/typings/registry/blob/master/schema.json.

**Comment by louy** [comment]
So why didn't we have the same problem with `console` in #8? Would adding the whole `Error` interface solve this?

**Comment by unional** [comment]
@louy Tried that, didn't work. Don't know why.

@blakeembrey , any idea? Would like to avoid further branching for compiler version.

**Comment by blakeembrey** [comment]
@unional I haven't commented since I personally haven't replicated. To be honest, I've been using these typings and TypeScript nightlies without any issue.

**Comment by blakeembrey** [comment]
Ok, nope. I don't have any solution. Looks like `stack` should be killed in 1.9 forward, what if we remove it and leave a notice in `typings.json/postmessage` about this change?

On a side note, are we going to node updates for v5 and v6?

**Comment by unional** [comment]
dt current is at v6. :)



> Looks like stack should be killed in 1.9 forward, what if we remove it and leave a notice in typings.json/postmessage about this change?

Instead of using `compiler` to specify it is for `1.9`? (by the way, would `1.9.0` works for `1.9.0-dev-....`? How to specify the compiler version on the cli?

**Comment by blakeembrey** [comment]
It's kind of messy right now since no one has used it, but you can specify registry tags using `typings i env~node#tag` where `tag === lookeduptag`. In this case, the compiler version is appended to the end up the tag.

**Comment by unional** [comment]
I tried `typings i env~node@10050df9e714121f730974cbaa7919215e158fa0 -SG` and it doesn't work.

```js
{
  "versions": {
    "0.8.0": "github:typed-typings/env-node/0.8#a36ce8a19f93da8798bf06e11ee34fd823e0b185",
    "0.10.0": "github:typed-typings/env-node/0.10#a36ce8a19f93da8798bf06e11ee34fd823e0b185",
    "0.11.0": "github:typed-typings/env-node/0.11#a36ce8a19f93da8798bf06e11ee34fd823e0b185",
    "0.12.0": "github:typed-typings/env-node/0.12#a36ce8a19f93da8798bf06e11ee34fd823e0b185",
    "4.0.0": [
      "github:typed-typings/env-node/4#a36ce8a19f93da8798bf06e11ee34fd823e0b185",
      {
        "compiler": "1.9.0",
        "description": "For TypeScript 1.9",
        "location": "github:typed-typings/env-node/4#10050df9e714121f730974cbaa7919215e158fa0" // <-- here
      }
    ]
  }
}
```
https://github.com/typings/registry/blob/master/env/node.json#L12
This is the lookeduptag you refer to?

**Comment by unional** [comment]
Also tried
`typings i env~node@4#10050df9e714121f730974cbaa7919215e158fa0 -SG`
`typings i env~node@10050df9e714121f730974cbaa7919215e158fa0 -SG`

**Comment by blakeembrey** [comment]
No, that's not the tag - it's the tag from the API not the git commit. It appears the back-end hasn't indexed that format correctly anyway though.

**Comment by unional** [comment]
How would I lookup the tag from API?
btw, this is also not working:
`typings i github:typed-typings/env-node#10050df9e714121f730974cbaa7919215e158fa0 -SG`

**Comment by blakeembrey** [comment]
It's not the commit. It's the tag from the API. See `tag` in https://api.typings.org/entries/env/node/versions.

**Comment by unional** [comment]
Got the `github` part working:
`https://raw.githubusercontent.com/typed-typings/env-node/10050df9e714121f730974cbaa7919215e158fa0/4 -SG`

**Comment by blakeembrey** [comment]
So the object format is currently failing to insert - need to check with the API code. 

![image](https://cloud.githubusercontent.com/assets/1088987/15586593/17dcf85a-233a-11e6-9e8c-a0c775e2ce0d.png)

**Comment by unional** [comment]
> It's not the commit. It's the tag from the API. See tag in

Got it. Need to find a way to expose. Probably in `typings info abc`?

**Comment by blakeembrey** [comment]
`typings info abc --versions` shows the tags.

**Comment by unional** [comment]
Thanks!

**Comment by louy** [comment]
I've just tried using `typescript@1.9.0-dev.20160529-1.0` and didn't get that error message about `Duplicate identifier 'stack'`.
