### ISSUE TITLE
readFileSync `options` can be null

### ISSUE THREAD

**Issue by cjbarth** [types/env-node#46]
`export function readFileSync(filename: string, options: ReadFileOptions): Buffer;`
and
`export function readFile(filename: string, options: ReadFileOptions, callback: (err: NodeJS.ErrnoException | null, data: Buffer) => void): void;`

should be:

`export function readFileSync(filename: string, options: ReadFileOptions | null): Buffer;`
and
`export function readFile(filename: string, options: ReadFileOptions | null, callback: (err: NodeJS.ErrnoException | null, data: Buffer) => void): void;`

I can create a PR if desired.

**Comment by blakeembrey** [comment]
Sure, I think that's reasonable. Currently it supports `undefined` instead of `null`. From node.js core: https://github.com/nodejs/node/blob/0bdd39f729a9c26a88cda964696b97bdaa2592d4/lib/fs.js#L40-L43.

**Comment by blakeembrey** [comment]
Thanks! Closed with your PR: https://github.com/types/env-node/pull/47.
