### ISSUE TITLE
Old definitions in registry

### ISSUE THREAD

**Issue by cjbarth** [types/env-node#48]
It seems that the typings registry has an old version of these typings. How can these be updated? I see two commits to master since these were last updated. Granted, one was just today, but the other was some days ago.

```
TAG                   VERSION DESCRIPTION COMPILER LOCATION                                                            UPDATED                 
6.0.0+20161105011511  6.0.0                        github:types/env-node/6.0#088b6275167df0e4bec9bee3205c703253ef4ace  2016-11-05T01:15:11.000Z
4.0.0+20161105011511  4.0.0                        github:types/env-node/4.0#088b6275167df0e4bec9bee3205c703253ef4ace  2016-11-05T01:15:11.000Z
0.12.0+20161105011511 0.12.0                       github:types/env-node/0.12#088b6275167df0e4bec9bee3205c703253ef4ace 2016-11-05T01:15:11.000Z
0.10.0+20161105011511 0.10.0                       github:types/env-node/0.10#088b6275167df0e4bec9bee3205c703253ef4ace 2016-11-05T01:15:11.000Z
```

**Comment by blakeembrey** [comment]
They're usually bumped manually from https://github.com/typings/registry/blob/master/env/node.json. I can quickly update them now, sometimes I can be a bit lazy and leave a few updates to collect before updating manually - when it's urgent, you can always use the GitHub URL or send a PR to speed it along 😄

**Comment by cjbarth** [comment]
That's good to know for the future. Thanks.
