### ISSUE TITLE
Broken with newest es6.lib.d.ts

### ISSUE THREAD

**Issue by felixfbecker** [types/env-node#49]
Definition of `WeakMap` in newest es6.lib.d.ts:
```ts
interface WeakMap<K extends object, V> { }

interface WeakMapConstructor {
    new <K extends object, V>(iterable: Iterable<[K, V]>): WeakMap<K, V>;
}
```
Definition in Node typings:
```ts
interface WeakMap<K, V> extends NodeWeakCollection {
  clear(): void;
  delete(key: K): boolean;
  get(key: K): V | void;
  has(key: K): boolean;
  set(key: K, value?: V): WeakMap<K, V>;
}

interface WeakMapConstructor extends NodeCollectionConstructor<WeakMap<any, any>> {
  new (): WeakMap<any, any>;
  new <K, V>(): WeakMap<K, V>;
}
```
Error:
```
typings/globals/node/index.d.ts(108,11): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
typings/globals/node/index.d.ts(118,25): error TS2344: Type 'K' does not satisfy the constraint 'object'.
```

Should we really define `WeakMap` in the Node typings if it is clearly part of ES6 spec and should therefor be provided by es6.lib.d.ts?

/cc @blakeembrey

**Comment by blakeembrey** [comment]
No, I think it should be deleted. All lib definitions can be removed from `node.d.ts` to avoid these sorts of issues, and luckily TS 2.0 made this easier with the `lib` config option.

**Comment by felixfbecker** [comment]
what confused me a bit though is that `WeakMap` has no methods in es6.lib.d.ts

**Comment by blakeembrey** [comment]
Do you want to take a look at https://github.com/types/env-node/pull/50?
