### ISSUE TITLE
7.0.8 Breaks when used with @types/Core-js

### ISSUE THREAD

**Issue by fluffywaffles** [types/env-node#52]
They disagree about the type of "iterator." The new version of @types/node states that the iterator is "readonly," whereas the most recent version of types for @types/core-js does not say  "readonly," resulting  in the following error:

```
504     iterator: symbol;
        ~~~~~~~~

node_modules/@types/core-js/index.d.ts(504,5): error TS2687: All declarations of 'iterator' must have identical modifiers.


50     readonly iterator: symbol;
                ~~~~~~~~

node_modules/@types/node/index.d.ts(50,14): error TS2687: All declarations of 'iterator' must have identical modifiers.

```

Unfortunately we're targeting Nodejs v4.3  (using AWS Lambda, which hasn't updated their node runtime in a long time and doesn't seem eager to do so soon), so we need some of the polyfills from core-js in order to make our code work.

**Comment by unional** [comment]
`node_modules/@typess/node` is installed using `npm i @types/node` and it is in DT, not this repo.

Please open an issue at DT instead. 🌷

**Comment by fluffywaffles** [comment]
Apologies. Thanks!

**Comment by unional** [comment]
No problem. Hope it will get resolved soon. 🌷
